### ISSUE TITLE
What's the exact meaning of each column field?

### ISSUE THREAD

**Issue by zxteloiv** [tzshi/squall#6]
Hi. Thanks for sharing the code. I'm confused about the column meaning.

From the introduction the column is said to be a quadruple.

> a list of processed table columns with the format of [raw header text, tokenized header text, available column suffixes (ways to interpret this column beyond raw texts), column data type]

But clearly a column contains five elements, as the columns from the first 100 instances.

> ["took office",["took","office"],["number","parsed","year","month","day"],"date","november 16, 1907"]
> ["top speed (km/h)",["top","speed","-lrb-","km\\\\/h","-rrb-"],[],"text","90 (1971)"]
> ["tornadoes",["tornadoes"],["number"],"number","66"]
> ["total\napps",["total","apps"],["number"],"number","40"]
> ["total\ngoals",["total","goals"],["number"],"number","2"]
> ["train",["train"],[],"text","transrapid 01"]
> ["type",["type"],[],"text","dnf"]
> ["uci world tour\npoints",["uci","world","tour","points"],["number"],"number","80"]
> ["until",["until"],["number","parsed","year"],"date","2011"]
> ["us dollar exchange",["us","dollar","exchange"],["number"],"unitnum","0.27 kuwaiti dinars"]
> ["venue",["venue"],["address"],"address","helsinki olympic stadium"]
> ["visiting team",["visiting","team"],[],"text","malta"]

What do the last three item mean?
In [vocab.py](https://github.com/tzshi/squall/blob/ee6dda91eacafd5ee800eb3fdc5d3a6575dc47e7/model/vocab.py#L26)  I read something like `col_type` based on c[3] and `columnt` based on c[2], and both fields have been used in model.
Though col_type seems only used for embedding lookup in the LSTM baseline, the decoder make an extensive usage of `columnt`.
Are they both the same (type of the column, like the names suggest)?
And why the c[2], c[3] are different in the examples and sometimes c[2] is an empty list?

Thanks again for reading this question!

**Comment by tzshi** [comment]
Hi,

The last element in each column tuple is the first data entry as an example of what this column contains.

`c[3]` is the column data types (see Appendix D), and `c[2]` contain available suffixes as possible ways to interpret the data according to the data type (Section 3.1). When `c[2]` is an empty list, that means the column can only be interpreted as raw texts (i.e., cannot be interpreted as numbers, etc. ) `col_type` (`c[3]`) is mostly used for encoding, but `columnt` (`c[2]`) is an integral part of the logical forms (see for example the logical forms in Figure 1), so it is used more extensively both as inputs and outputs of the models.

Hope this explanation helps.

**Comment by zxteloiv** [comment]
Thanks very much for the information!
Then I read that c[3] is a WTQ data type and c[2] is a parsed type (I've found them corresponding to the sqlite tables under the tables/db directory)
Thanks again for your help!
